/*
 * nanortc examples — Linux event loop (select-based)
 *
 * Reference: design doc §5.3
 *
 * SPDX-License-Identifier: MIT
 */

#include "run_loop.h"
#include "nano_rtc_internal.h"

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/select.h>

uint32_t nano_get_millis(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint32_t)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}

int nano_run_loop_init(nano_run_loop_t *loop, nanortc_t *rtc,
                       const char *bind_ip, uint16_t port)
{
    if (!loop || !rtc) {
        return -1;
    }

    memset(loop, 0, sizeof(*loop));
    loop->rtc = rtc;
    loop->port = port;
    loop->running = 0;

    /* Create UDP socket */
    loop->fd = socket(AF_INET, SOCK_DGRAM, 0);
    if (loop->fd < 0) {
        perror("socket");
        return -1;
    }

    int reuse = 1;
    setsockopt(loop->fd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));

    struct sockaddr_in local;
    memset(&local, 0, sizeof(local));
    local.sin_family = AF_INET;
    local.sin_port = htons(port);
    if (bind_ip) {
        inet_pton(AF_INET, bind_ip, &local.sin_addr);
    } else {
        local.sin_addr.s_addr = INADDR_ANY;
    }

    if (bind(loop->fd, (struct sockaddr *)&local, sizeof(local)) < 0) {
        perror("bind");
        close(loop->fd);
        loop->fd = -1;
        return -1;
    }

    /* Register local candidate */
    char ip_str[INET_ADDRSTRLEN] = "0.0.0.0";
    if (bind_ip) {
        strncpy(ip_str, bind_ip, sizeof(ip_str) - 1);
    }
    nanortc_add_local_candidate(rtc, ip_str, port);

    return 0;
}

void nano_run_loop_set_event_cb(nano_run_loop_t *loop,
                                nano_event_cb cb, void *userdata)
{
    if (loop) {
        loop->event_cb = cb;
        loop->event_userdata = userdata;
    }
}

static void dispatch_outputs(nano_run_loop_t *loop, uint32_t *timeout_ms)
{
    nanortc_output_t out;

    while (nanortc_poll_output(loop->rtc, &out) == NANORTC_OK) {
        switch (out.type) {
        case NANORTC_OUTPUT_TRANSMIT: {
            struct sockaddr_in dest;
            memset(&dest, 0, sizeof(dest));
            dest.sin_family = AF_INET;
            memcpy(&dest.sin_addr, out.transmit.dest.addr, 4);
            dest.sin_port = htons(out.transmit.dest.port);

            sendto(loop->fd, out.transmit.data, out.transmit.len, 0,
                   (struct sockaddr *)&dest, sizeof(dest));
            break;
        }
        case NANORTC_OUTPUT_EVENT:
            if (loop->event_cb) {
                loop->event_cb(loop->rtc, &out.event, loop->event_userdata);
            }
            break;

        case NANORTC_OUTPUT_TIMEOUT:
            if (out.timeout_ms < *timeout_ms) {
                *timeout_ms = out.timeout_ms;
            }
            break;
        }
    }
}

int nano_run_loop_step(nano_run_loop_t *loop)
{
    if (!loop || loop->fd < 0) {
        return -1;
    }

    uint32_t timeout_ms = 100; /* default poll interval */

    /* Drain output queue */
    dispatch_outputs(loop, &timeout_ms);

    /* Wait for network input or timeout */
    fd_set rset;
    FD_ZERO(&rset);
    FD_SET(loop->fd, &rset);

    struct timeval tv = {
        .tv_sec = timeout_ms / 1000,
        .tv_usec = (timeout_ms % 1000) * 1000,
    };

    int ret = select(loop->fd + 1, &rset, NULL, NULL, &tv);
    uint32_t now = nano_get_millis();

    if (ret > 0 && FD_ISSET(loop->fd, &rset)) {
        uint8_t buf[1500];
        struct sockaddr_in from;
        socklen_t fromlen = sizeof(from);

        ssize_t n = recvfrom(loop->fd, buf, sizeof(buf), 0,
                             (struct sockaddr *)&from, &fromlen);
        if (n > 0) {
            nanortc_addr_t src;
            memset(&src, 0, sizeof(src));
            src.family = 4;
            memcpy(src.addr, &from.sin_addr, 4);
            src.port = ntohs(from.sin_port);

            nanortc_handle_receive(loop->rtc, now, buf, (size_t)n, &src);
        }
    } else {
        nanortc_handle_timeout(loop->rtc, now);
    }

    /* Dispatch any new output generated by handle_receive/timeout */
    dispatch_outputs(loop, &timeout_ms);

    return 0;
}

int nano_run_loop_run(nano_run_loop_t *loop)
{
    if (!loop) {
        return -1;
    }

    loop->running = 1;
    while (loop->running) {
        int rc = nano_run_loop_step(loop);
        if (rc < 0) {
            return rc;
        }
    }
    return 0;
}

void nano_run_loop_stop(nano_run_loop_t *loop)
{
    if (loop) {
        loop->running = 0;
    }
}

void nano_run_loop_destroy(nano_run_loop_t *loop)
{
    if (loop && loop->fd >= 0) {
        close(loop->fd);
        loop->fd = -1;
    }
}
